### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "void com.navercorp.nid.oauth.OAuthLoginCallback.onError(int, java.lang.String)"

### ISSUE THREAD

**Issue by Bingoliallen** [naver/naveridlogin-sdk-android#117]
From Naver Game SDK startHome to Naver App Oauth Login：
1、navergame-sdk-gradle-1.3.3.aar
2、implementation 'com.navercorp.nid:oauth-jdk8:5.9.1'

Crash：
java.lang.AbstractMethodError: abstract method "void com.navercorp.nid.oauth.OAuthLoginCallback.onError(int, java.lang.String)"
        at com.navercorp.nid.oauth.NidOAuthBridgeActivity.oauthFinish(NidOAuthBridgeActivity.kt:318)
        at com.navercorp.nid.oauth.NidOAuthBridgeActivity.finishWithErrorResult(NidOAuthBridgeActivity.kt:310)
        at com.navercorp.nid.oauth.NidOAuthBridgeActivity.onActivityResult(NidOAuthBridgeActivity.kt:335)
        at android.app.Activity.dispatchActivityResult(Activity.java:7462)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4401)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4450)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6825)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
2024-07-18 16:40:21.827 1571-1659/system_process E/InputDispatcher: channel 'e53b1e5 com.qc.snd.kr.gp/com.navercorp.nid.oauth.NidOAuthBridgeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by yu-ri-mun** [comment]
Hello, @Bingoliallen.
I'm an Android Developer for Naver Id Login SDK.

Sorry for the delayed response.

`Naver Game SDK v1.3.3` is compatible with `NAVER Login SDK v5.8.0`. 
Please verify that you are using v5.8.0 in your environment.

If the problem continues after the update, please submit a new report to us.

Thank you.
