### ISSUE TITLE
initialize 후 authenticate 호출하는데 오류가 발생합니다.

### ISSUE THREAD

**Issue by Saebyeol98** [naver/naveridlogin-sdk-android#22]
authenticate 내부 코드에서 Intent를 요청할때 FLAG가 설정이 안되어 있는지 System.err 이 발생합니다.

    /**
     * OAuth 2.0 로그인을 수행한다.
     *
     * RefreshToken이 존재하는 경우, 이미 연동이 된 것이므로 AccessToken을 갱신해준다.
     *
     * @param context authenticate 메서드를 호출한 Activity의 Context
     * @param callback 결과값을 받을 콜백
     */
    fun authenticate(context: Context, callback: OAuthLoginCallback) {
        if (getState() == NidOAuthLoginState.NEED_INIT) {
            Toast.makeText(context.applicationContext, "SDK 초기화가 필요합니다.", Toast.LENGTH_SHORT).show()
            return
        }

        oauthLoginCallback = callback

        val refreshToken = getRefreshToken()
        if (refreshToken.isNullOrEmpty()) {
            val intent = Intent(context, NidOAuthBridgeActivity::class.java)
            val orientation = context.resources.configuration.orientation
            intent.putExtra("orientation", orientation)
            context.startActivity(intent)
        } else {
            NidOAuthLogin().refreshToken(context, callback)
        }
    }

오류 로그는 다음과 같습니다.

2022-02-10 19:13:44.271 23234-25141/com.example.naverlogin W/System.err: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:995)
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at android.app.ContextImpl.startActivity(ContextImpl.java:971)
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:102)
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at com.sortielab.sumstation.MainActivity.startNaverLogin(MainActivity.kt:156)
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at com.sortielab.sumstation.SumStationBridge.requestNaverLogin(SumStationBridge.kt:111)
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at android.os.Looper.loop(Looper.java:197)
2022-02-10 19:13:44.271 23234-25141/com.sortielab.sumstation W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by dalcomdev** [comment]
sdk 수정없이 가능한 방법은, 호출하는 Activity 에서 flag FLAG_ACTIVITY_NEW_TASK 설정해 주시고, Activity 를 authenticate 의 첫번째 파라마티로 전달해 주시면 될거 같습니다.
참고: https://github.com/naver/naveridlogin-sdk-android/issues/24

제 생각에도, 네아로에서 FLAG_ACTIVITY_NEW_TASK flag 를 설정하면 좋을것 같은데요. sdk 수정을 고려 부탁드립니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.
네아로SDK 담당자입니다.
해당 이슈는 v5.1.0 버전부터 해소되었습니다.
감사합니다.
