### ISSUE TITLE
Non Activity class 에서 NaverIdLoginSDK.authenticate 호출시 exception

### ISSUE THREAD

**Issue by dalcomdev** [naver/naveridlogin-sdk-android#24]
Non Activity class 에서 NaverIdLoginSDK.authenticate 호출시 exception 발생합니다.
해당 Activity 에 FLAG_ACTIVITY_NEW_TASK flag 추가 요청 드립니다.

```kotlin
    android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:1131)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1107)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:420)
        at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:102)
```

**Comment by dalcomdev** [comment]
호출하는 Activity 에서 flag 추가하여 정상동작 합니다.
