### ISSUE TITLE
kotlin.UninitializedPropertyAccessException 에러

### ISSUE THREAD

**Issue by cherry-cherry-sun** [naver/naveridlogin-sdk-android#32]
NidOAuthBridgeActivity.onActivityResult() 에서 
data가 null 인경우, NaverIdLoginSDK.oauthLoginCallback 이 초기화 되지 않아 에러가 발생합니다. 
재현은 해볼려고 하는데 잘 되지 않네요.
```
Caused by kotlin.UninitializedPropertyAccessException: lateinit property oauthLoginCallback has not been initialized
       at com.navercorp.nid.NaverIdLoginSDK.getOauthLoginCallback(NaverIdLoginSDK.kt:39)
       at com.navercorp.nid.oauth.NidOAuthBridgeActivity.oauthFinish(NidOAuthBridgeActivity.kt:269)
       at com.navercorp.nid.oauth.NidOAuthBridgeActivity.finishWithErrorResult(NidOAuthBridgeActivity.kt:260)
       at com.navercorp.nid.oauth.NidOAuthBridgeActivity.onActivityResult(NidOAuthBridgeActivity.kt:284)
       at android.app.Activity.dispatchActivityResult(Activity.java:8550)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5583)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4905)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4955)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by whath** [comment]
hey, we are facing the same, do we have a plan for that fix? thanks

**Comment by whath** [comment]
hey @https-namhoon-kim 
 We have been plagued by this issue currently and for the past few months, do we have any plans to fix it?

**Comment by DayeonLee-0** [comment]
안녕하세요. 네아로SDK 담당자입니다.

해당 이슈는 v5.2.0 버전부터 해소되었습니다.

감사합니다.
