### ISSUE TITLE
네이버 로그인 초기화시 InvalidProtocolBufferException 발생

### ISSUE THREAD

**Issue by lhb2435TW** [naver/naveridlogin-sdk-android#37]
네아로 5.0.1 사용중입니다. 안드로이드 12기기에서 아래 오류가 발생합니다. 네아로에서 사용중인 crypto 라이브러리(androidx.security:security-crypto:1.1.0-alpha03)에서 발생하는 문제같습니다. 

관련 문서: https://github.com/google/tink/issues/413#issuecomment-690914567

☛ 앱 설정에서 데이터 삭제한 후 앱 실행하면 오류가 안나네요

java.lang.RuntimeException: Unable to create application : com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7511)
        at android.app.ActivityThread.access$1700(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
        at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
        at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:22)
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:13)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:18)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:17)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:17)
        at com.navercorp.nid.oauth.EncryptedPreferences.set(EncryptedPreferences.kt:69)
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.setClientId(NidOAuthPreferencesManager.kt:52)
        at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:56)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
        at android.app.ActivityThread.access$1700(ActivityThread.java:310) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8663) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.4.0부터 Google tink 초기화 이슈에 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
