### ISSUE TITLE
네이버 아이디 로그인시 에러 발생(java.lang.IllegalArgumentException)

### ISSUE THREAD

**Issue by jeabual** [naver/naveridlogin-sdk-android#41]
네이버 아이디 로그인시 간헐적으로 Crash Report 되고 있습니다.
확인 부탁드립니다.
SDK 버전은 5.1.0 입니다.

Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@3aecdd8[NidOAuthBridgeActivity] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:648)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:548)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:162)
       at android.app.Dialog.dismissDialog(Dialog.java:778)
       at android.app.Dialog.dismiss(Dialog.java:754)
       at androidx.appcompat.app.AppCompatDialog.dismiss(AppCompatDialog.java:140)
       at com.navercorp.nid.progress.NidProgressDialog.hideProgress(NidProgressDialog.java:73)
       at com.navercorp.nid.oauth.NidOAuthLogin$accessToken$1.invokeSuspend(NidOAuthLogin.java:239)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by DayeonLee-0** [comment]
안녕하세요. 네아로SDK 담당자입니다.

해당 이슈는 v5.2.0 버전부터 해소되었습니다.

감사합니다.
