### ISSUE TITLE
5.1.1 네아로 호출시 오류가 발생합니다.

### ISSUE THREAD

**Issue by Saebyeol98** [naver/naveridlogin-sdk-android#47]
2022-06-24 13:57:01.847 2415-2415/com.?.? W/AndroidKeystoreAesGcm: encountered a potentially transient KeyStore error, will wait and retry
    javax.crypto.AEADBadTagException
        at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:617)
        at javax.crypto.Cipher.doFinal(Cipher.java:2113)
        at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:115)
        at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:97)
        at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:206)
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:107)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:32)
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:16)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:28)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:27)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:27)
        at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:84)
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:53)
        at com.navercorp.nid.oauth.EncryptedPreferences.migration(EncryptedPreferences.kt:110)
        at com.navercorp.nid.oauth.EncryptedPreferences.setContext(EncryptedPreferences.kt:44)
        at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:56)
        at com.?.?.MainActivity.startNaverLogin$lambda-9(MainActivity.kt:484)
        at com.?.?.MainActivity.$r8$lambda$_fmXxE5yS5OybJ5uyqlDD8OuIS4(Unknown Source:0)
        at com.?.?.MainActivity$$ExternalSyntheticLambda2.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: android.security.KeyStoreException: Signature/MAC verification failed
        at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:408)
        at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
        at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:127)
        at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
        at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
        at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
        at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:609)
        at javax.crypto.Cipher.doFinal(Cipher.java:2113) 
        at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:115) 
        at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:97) 
        at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:206) 
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:107) 
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311) 
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287) 
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238) 
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155) 
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120) 
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:32) 
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:16) 
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:28) 
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:27) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:27) 
        at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:84) 
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:53) 
        at com.navercorp.nid.oauth.EncryptedPreferences.migration(EncryptedPreferences.kt:110) 
        at com.navercorp.nid.oauth.EncryptedPreferences.setContext(EncryptedPreferences.kt:44) 
        at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:56) 
        at com.?.?.MainActivity.startNaverLogin$lambda-9(MainActivity.kt:484) 
        at com.?.?.MainActivity.$r8$lambda$_fmXxE5yS5OybJ5uyqlDD8OuIS4(Unknown Source:0) 
        at com.?.?.MainActivity$$ExternalSyntheticLambda2.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
2022-06-24 13:57:01.925 2415-2415/com.?.? W/AndroidKeysetManager: cannot decrypt keyset: 
    javax.crypto.AEADBadTagException
        at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:617)
        at javax.crypto.Cipher.doFinal(Cipher.java:2113)
        at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:115)
        at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:101)
        at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:206)
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:107)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:32)
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:16)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:28)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:27)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:27)
        at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:84)
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:53)
        at com.navercorp.nid.oauth.EncryptedPreferences.migration(EncryptedPreferences.kt:110)
        at com.navercorp.nid.oauth.EncryptedPreferences.setContext(EncryptedPreferences.kt:44)
        at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:56)
        at com.?.?.MainActivity.startNaverLogin$lambda-9(MainActivity.kt:484)
        at com.?.?.MainActivity.$r8$lambda$_fmXxE5yS5OybJ5uyqlDD8OuIS4(Unknown Source:0)
        at com.?.?.MainActivity$$ExternalSyntheticLambda2.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: android.security.KeyStoreException: Signature/MAC verification failed
        at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:408)
        at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
        at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:127)
        at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
        at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
        at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
        at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:609)
        at javax.crypto.Cipher.doFinal(Cipher.java:2113) 
        at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:115) 
        at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:101) 
        at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:206) 
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:107) 
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311) 
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287) 
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238) 
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155) 
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120) 
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:32) 
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:16) 
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:28) 
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:27) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:27) 
        at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:84) 
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:53) 
        at com.navercorp.nid.oauth.EncryptedPreferences.migration(EncryptedPreferences.kt:110) 
        at com.navercorp.nid.oauth.EncryptedPreferences.setContext(EncryptedPreferences.kt:44) 
        at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:56) 
        at com.?.?.MainActivity.startNaverLogin$lambda-9(MainActivity.kt:484) 
        at com.?.?.MainActivity.$r8$lambda$_fmXxE5yS5OybJ5uyqlDD8OuIS4(Unknown Source:0) 
        at com.?.?.MainActivity$$ExternalSyntheticLambda2.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
2022-06-24 13:57:01.926 2415-2415/com.?.? D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.?.?, PID: 2415
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
     Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
        at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
        at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:32)
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:16)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:28)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:27)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:27)
        at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:84)
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:53)
        at com.navercorp.nid.oauth.EncryptedPreferences.migration(EncryptedPreferences.kt:110)
        at com.navercorp.nid.oauth.EncryptedPreferences.setContext(EncryptedPreferences.kt:44)
        at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:56)
        at com.?.?.MainActivity.startNaverLogin$lambda-9(MainActivity.kt:484)
        at com.?.?.MainActivity.$r8$lambda$_fmXxE5yS5OybJ5uyqlDD8OuIS4(Unknown Source:0)
        at com.?.?.MainActivity$$ExternalSyntheticLambda2.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 

기종별로 뭔가 다른점이있는지             
 NaverIdLoginSDK.initialize(
                context,
                NAVER_CLIENT_ID,
                NAVER_SECRET_KEY,
                NAVER_CLIENT_NAME
            ) 
를 호출하는데  SM-F926N (폴드 3) 에서는 오류가 발생하지 않으나
SM-G986N (S20+ 5G) 기종에서 사용할때 해당 오류와 함께 강제종료가 발생합니다.
둘다 OS 버전은 Android 12 SDK 31 입니다

앱 패키지 명은 com.?.? 로 가린점 양해 부탁드립니다.
오류 확인부탁드립니다.

**Comment by schneider-banana** [comment]
저도 같은오류네요
z플립3 에서는 오류발생하지만
갤럭시s22 에서는 잘됩니다.

**Comment by loca961** [comment]
갤럭시 플립4(SM-F721N) api 32 안나오던 위 오류가 갑자기 나타났습니다.
정상적으로 이용중이었는데, 오늘 확인해보니 오류가 나네요.
노트20(SM-N981N) api 31 에서는 나타나지 않고 있습니다.
에뮬레이터 api 32 에서는 발생을 안하고..
왜 안나던 오류가 갑자기 나는 걸까요.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.4.0부터 Google tink 초기화 이슈에 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.

**Comment by contigo** [comment]
5.7.0 SDK사용중인데 
폴드4에서 동일증상이 생깁니다

**Comment by boomto7** [comment]
5.7.0 sdk에 z플립 3에서도 동일한 증상이 생깁니다.

**Comment by contigo** [comment]
앱의 앱정보 -> 저장공간 -> 데이터 지우기를 하면 안나타나긴 합니다 

> 5.7.0 sdk에 z플립 3에서도 동일한 증상이 생깁니다.
