### ISSUE TITLE
5.1.1 로그인 크래쉬

### ISSUE THREAD

**Issue by mk0116** [naver/naveridlogin-sdk-android#48]
최초 1회는 동작하고, 로그인이 되어있는 상태에서 로그인을 호출하면 발생하는 문제입니다.

2022-06-27 16:37:50.336 12523-12523/co.aienglish E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.aienglish, PID: 12523
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at com.navercorp.nid.progress.NidProgressDialog.init(NidProgressDialog.kt:39)
        at com.navercorp.nid.progress.NidProgressDialog.<init>(NidProgressDialog.kt:32)
        at com.navercorp.nid.oauth.NidOAuthLogin.refreshToken(NidOAuthLogin.kt:198)
        at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:113)
        at com.dooboolab.naverlogin.RNNaverLoginModule$1.run(RNNaverLoginModule.java:131)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7850)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by namse** [comment]
어떻게 해결하셨는지 알 수 있을까요?
