### ISSUE TITLE
android.util.AndroidRuntimeException: requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by yellowdo** [naver/naveridlogin-sdk-android#50]
Caused by android.util.AndroidRuntimeException: requestFeature() must be called before adding content
       at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:396)
       at android.app.Activity.requestWindowFeature(Activity.java:5110)
       at com.navercorp.nid.oauth.activity.NidOAuthWebViewActivity.onCreate(NidOAuthWebViewActivity.kt:67)
       at android.app.Activity.performCreate(Activity.java:8071)
       at android.app.Activity.performCreate(Activity.java:8051)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7952)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

5.1.1 버전에서 발생, NidOAuthWebViewActivity 67line 에서 문제가 발생하고 있습니다.

**Comment by HQHAN** [comment]
저도 동일 이슈 발생중입니다.
빠른 확인 부탁드립니다.

**Comment by HQHAN** [comment]
현재 상용 서비스에 네이버 로그인을 SDK 연동해서 적용했는데  Crashlytics 에서 해당 에러 발생중입니다. 
`requestWindowFeature`가  `setContentView` 보다 앞서 호출되도록 보장해주면 되는 이슈인데 빠른 수정 부탁 드립니다.

**Comment by DayeonLee-0** [comment]
안녕하세요. 

네아로 SDK 담당자입니다.

리폿해주신 이슈는 `NidOAuthWebViewActivity`에서 발생하는 이슈로 v5.2.0 버전부터 `WebView`가 제거되어 발생하지 않습니다.

참고 부탁드립니다.

감사합니다.
