### ISSUE TITLE
com.google.crypto.tink.shaded.protobuf.c0: Protocol message contained an invalid tag (zero)

### ISSUE THREAD

**Issue by mym0404** [naver/naveridlogin-sdk-android#59]
- SDK `5.2.0`

다음과 같은 issue가 발생합니다.

`com.navercorp.nid.NaverIdLoginSDK.getLastErrorCode(NaverIdLoginSDK.kt:148)` 를 부를 때 입니다.

주 원인은 [issue](https://github.com/google/tink/issues/504) 로 보이며, 해당 Exception이 발생한 경우 EncryptedSharedPreferences의 초기화에서 파일 이름을 변경해주는 로직을 넣어야 할 것 같습니다.

아니면 jetpack security 쪽의 업데이트를 기다려야 할 것 같습니다.

```shell
Caused by com.google.crypto.tink.shaded.protobuf.c0: Protocol message contained an invalid tag (zero).
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1663)
       at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
       at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
       at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
       at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:34)
       at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:17)
       at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:30)
       at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:29)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:29)
       at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:86)
       at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getLastErrorCode(NidOAuthPreferencesManager.kt:84)
       at com.navercorp.nid.NaverIdLoginSDK.getLastErrorCode(NaverIdLoginSDK.kt:148)
       at com.dooboolab.naverlogin.RNNaverLoginModule$Companion.createLoginFailureResponse(RNNaverLoginModule.kt:143)
       at com.dooboolab.naverlogin.RNNaverLoginModule$Companion.onLoginFailure(RNNaverLoginModule.kt:125)
       at com.dooboolab.naverlogin.RNNaverLoginModule$Companion.access$onLoginFailure(RNNaverLoginModule.kt:101)
       at com.dooboolab.naverlogin.RNNaverLoginModule.login$lambda-1(RNNaverLoginModule.kt:88)
       at com.dooboolab.naverlogin.RNNaverLoginModule.$r8$lambda$9DhD-bSQORgiqNoOhxh4y3p9nl8(RNNaverLoginModule.kt)
       at com.dooboolab.naverlogin.RNNaverLoginModule$$InternalSyntheticLambda$0$dc93727e2d141454a50d11f5e02e4f0b65846d86912d8151f7fbbf5793324763$0.run(RNNaverLoginModule.java:10)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7882)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.4.0부터 Google tink 초기화 이슈에 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
