### ISSUE TITLE
release 빌드에서만 lateinit property launcher has not been initialized, null 에러가 발생합니다.

### ISSUE THREAD

**Issue by kghoon** [naver/naveridlogin-sdk-android#65]
```
I/flutter ( 2680): [LoginBloc] PlatformException(error, lateinit property launcher has not been initialized, null, kotlin.x: lateinit property launcher has not been initialized
I/flutter ( 2680): 	at g.n.a.b.d(Unknown Source:24)
I/flutter ( 2680): 	at g.n.a.b.onMethodCall(Unknown Source:20)
I/flutter ( 2680): 	at j.a.d.a.k$a.a(Unknown Source:17)
I/flutter ( 2680): 	at io.flutter.embedding.engine.f.e.k(Unknown Source:18)
I/flutter ( 2680): 	at io.flutter.embedding.engine.f.e.l(Unknown Source:20)
I/flutter ( 2680): 	at io.flutter.embedding.engine.f.e.m(Unknown Source:0)
I/flutter ( 2680): 	at io.flutter.embedding.engine.f.c.run(Unknown Source:12)
I/flutter ( 2680): 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter ( 2680): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter ( 2680): 	at android.os.Looper.loopOnce(Looper.java:226)
I/flutter ( 2680): 	at android.os.Looper.loop(Looper.java:313)
I/flutter ( 2680): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
I/flutter ( 2680): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 2680): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
I/flutter ( 2680): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/flutter ( 2680): )
I/flutter ( 2680): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
I/flutter ( 2680): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #2      FlutterNaverLogin.logIn (package:flutter_naver_login/flutter_naver_login.dart:11)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #3      NaverUtil.login (package:woodong/src/api/naver_api.dart:23)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #4      LoginBloc.checkUserSignedUp (package:woodong/src/bloc/login/login_bloc.dart:53)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #5      _LoginState.ssoLogin (package:woodong/src/ui/screen/login/login_screen.dart:81)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): #6      _LoginState.build.<anonymous closure>.<anonymous closure> (package:woodong/src/ui/screen/login/login_screen.dart:131)
I/flutter ( 2680): <asynchronous suspension>
I/flutter ( 2680): {code: -401, msg: this access token does not exist}
```

릴리즈 빌드에서만 발생하는 문제입니다. 'launcher' property 가 준비가 안될걸로 봐서 onAttachedToActivity 가 호출이 안되었거나, 타이밍 문제가 있는 것 같습니다.

**Comment by kghoon** [comment]
version 1.2.2 를 사용중입니다.
