### ISSUE TITLE
5.2.1에서 NaverIdLoginSDK.initialize 에서 발생하는 문제

### ISSUE THREAD

**Issue by k-hyeyun** [naver/naveridlogin-sdk-android#67]
일부 기기에서 NaverIdLoginSDK.initialize에서 강제종료 현상이 나타나고 있습니다.
현재 확인한 건 Galaxy Z Flip3 5G에서는 강제종료 현상이 나타나고, LG VELVET에서는 강제종료 현상은 나타나지 않고 있습니다.

W/AndroidKeysetManager: keyset not found, will generate a new one
    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_value_keyset__ does not exist
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:160)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:34)
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:17)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:30)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:29)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:29)
        at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:86)
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:53)
        at com.navercorp.nid.oauth.EncryptedPreferences.migration(EncryptedPreferences.kt:112)
        at com.navercorp.nid.oauth.EncryptedPreferences.setContext(EncryptedPreferences.kt:46)
        at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:58)
        at com.hibud.whizkizmom.MainApp.onCreate(MainApp.kt:42)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1212)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6816)
        at android.app.ActivityThread.access$1500(ActivityThread.java:248)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7952)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

아래에는 z flip 3의 crashlytics 내용입니다.
Caused by com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException
Protocol message contained an invalid tag (zero).

com.navercorp.nid.oauth.EncryptedPreferences.init (EncryptedPreferences.kt:34)

**Comment by 0biny** [comment]
manifest 에 dataExtractionRules이나 fullBackupContent  사용하시나요?

**Comment by k-hyeyun** [comment]
아니요, 사용하지 않습니다.

2022년 11월 25일 (금) 오후 4:41, yuan ***@***.***>님이 작성:

**Comment by raccoondev85** [comment]
저도 같은 에러가 나타납니다
implementation 'com.navercorp.nid:oauth:5.2.1' 으로 가져왔습니다

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.4.0부터 Google tink 초기화 이슈에 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
