### ISSUE TITLE
5.2.1 버전에서 com.navercorp.nid.NaverIdLoginSDK.initialize 에러 발생

### ISSUE THREAD

**Issue by gudals1947** [naver/naveridlogin-sdk-android#70]
안녕하세요.
다름이 아니라 현재 5.2.1 버전에서 sdk를 **init** 할 경우 오류가 발생하고 있습니다.
한번 확인 부탁 드립니다.
테스트 환경은 밑에 참고 부탁 드립니다.

## 오류 내용

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Caused by: java.lang.reflect.InvocationTargetException at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).

at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
at com.navercorp.nid.oauth.EncryptedPreferences.migration(EncryptedPreferences.kt:130)
at com.navercorp.nid.oauth.EncryptedPreferences.setContext(EncryptedPreferences.kt:46)
at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:58)

## 테스트 환경

- Android Ver : 13, 12
- Device : 갤럭시 s22, 갤럭시 z플립3
- hilt 의존성 주입 된 상태
- 네이버 앱 다운 받아진 상태
---

더 필요한 정보가 있으면 코멘트 남겨주시면 감사하겠습니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.4.0부터 Google tink 초기화 이슈에 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
