### ISSUE TITLE
5.4.0  NaverIdLoginSDK.initialize  오류 문의드립니다.

### ISSUE THREAD

**Issue by Yong-Dd** [naver/naveridlogin-sdk-android#76]
안녕하세요
5.4.0 이전 버전에서 사용하고 있었는데 하단과 동일한 오류가 나서 5.4.0으로 버전업 했구요
(com.navercorp.nid:oauth-jdk8:5.4.0)
EncryptedPreferences.java line 33 - Caused by zi.m lateinit property context has not been initialized 오류는 나고 있지 않지만
LG Q8에서는 정상적인데 폴드3와 S10+에서는 오류가 나서 강제 종료가 되고 있습니다.

폴드 3에서의 오류
Caused by qc.z
Protocol message contained an invalid tag (zero).

s10+에서의 오류
Caused by rc.z
While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either that the input has been truncated or that an embedded message misreported its own length.

여러 시도를 했지만 해결이 안 되고 있어서 혹시 어떻게 해결해야 할지 알려주시길 부탁드립니다.
감사합니다.

**Comment by ienground** [comment]
저도 항상은 아닌데 같은 오류가 뜨네요.

`Caused by d9.z: Protocol message contained an invalid tag (zero).
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:7)
       at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:2)
       at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:2)
       at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:2)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:2)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:2)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:13)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:10)
       at com.navercorp.nid.preference.EncryptedPreferences.createSharedPreferences(EncryptedPreferences.java:3)
       at com.navercorp.nid.preference.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.java:2)
       at kotlin.SynchronizedLazyImpl.getValue(SynchronizedLazyImpl.java:20)
       at com.navercorp.nid.preference.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.java:2)
       at com.navercorp.nid.preference.EncryptedPreferences.get(EncryptedPreferences.java:6)
       at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.java:5)
       at com.navercorp.nid.preference.EncryptedPreferences.migration(EncryptedPreferences.java:1)
       at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.java:29)
       at net.ienlab.blogplanner.activity.MainActivity.onCreate(MainActivity.java:22)
       at android.app.Activity.performCreate(Activity.java:8591)
       at android.app.Activity.performCreate(Activity.java:8570)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by DayeonLee-0** [comment]
안녕하세요.

Android 네아로 SDK 담당자입니다.

난독화 이슈로 Preference workaround 적용이 되지 않은것으로 보입니다.

아래 프로가드를 적용 후 네아로 SDK 최신버전(v5.8.0)으로 확인 부탁드립니다.

```
-keep class com.google.** { *; }
```

감사합니다.
