### ISSUE TITLE
[Bug Report] android.view.WindowLeaked: Activity com.navercorp.nid.oauth.NidOAuthBridgeActivity has leaked window DecorView@cdc1204[NidOAuthBridgeActivity] that was originally added here

### ISSUE THREAD

**Issue by sun5066** [naver/naveridlogin-sdk-android#84]
# Bug Report
### 사용중인 네아로 SDK 버전
v5.5.0

### Android 버전
12

### 재현되는 기기 모델명
갤럭시 노트 10 5G

### 재현 시나리오
로그인 버튼 클릭 -> 네이버 아이디 로그인 중 이라는 Dialog 나옴 -> 닫힐 때 에러로그 발생(크래시는 발생안함)

### Stack trace
```
android.view.WindowLeaked: Activity com.navercorp.nid.oauth.NidOAuthBridgeActivity has leaked window DecorView@cdc1204[NidOAuthBridgeActivity] that was originally added here
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1168)
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1143)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:490)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
                                                                                                    	at android.app.Dialog.show(Dialog.java:512)
                                                                                                    	at com.navercorp.nid.progress.NidProgressDialog.showProgress(NidProgressDialog.kt:72)
                                                                                                    	at com.navercorp.nid.progress.NidProgressDialog.showProgress(NidProgressDialog.kt:55)
                                                                                                    	at com.navercorp.nid.progress.NidProgressDialog.showProgress(NidProgressDialog.kt:47)
                                                                                                    	at com.navercorp.nid.oauth.NidOAuthBridgeActivity.onCreate$lambda-1(NidOAuthBridgeActivity.kt:121)
                                                                                                    	at com.navercorp.nid.oauth.NidOAuthBridgeActivity.$r8$lambda$QJ-6sD4x6uzbWG8ESEwSrwsppO8(Unknown Source:0)
                                                                                                    	at com.navercorp.nid.oauth.NidOAuthBridgeActivity$$ExternalSyntheticLambda1.onChanged(Unknown Source:4)
                                                                                                    	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                                                                                                    	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                                                                                                    	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                                                                                                    	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
                                                                                                    	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by yerinnnnn** [comment]
저도 동일한 이슈 발생합니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

해당 이슈는 네아로 SDK v5.6.0에서 해소되었습니다.

개발에 참고 부탁드립니다.

감사합니다.

**Comment by sun5066** [comment]
고생하셨습니다!!
