### ISSUE TITLE
[Bug Report] com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException 오류

### ISSUE THREAD

**Issue by ehgusrkwhr** [naver/naveridlogin-sdk-android#85]
해당 오류가 나는데 혹시 해결하신 분 있으신가요>
Caused by com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: CodedInputStream encountered an embedded string or message which claimed to have negative size.
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
       at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
       at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
       at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
       at com.navercorp.nid.preference.EncryptedPreferences.createSharedPreferences(EncryptedPreferences.kt:55)
       at com.navercorp.nid.preference.EncryptedPreferences.init(EncryptedPreferences.kt:40)
       at com.navercorp.nid.preference.EncryptedPreferences.access$init(EncryptedPreferences.kt:18)
       at com.navercorp.nid.preference.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:31)
       at com.navercorp.nid.preference.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:30)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.navercorp.nid.preference.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:30)
       at com.navercorp.nid.preference.EncryptedPreferences.get(EncryptedPreferences.kt:107)
       at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:54)
       at com.navercorp.nid.preference.EncryptedPreferences.migration(EncryptedPreferences.kt:133)
       at com.navercorp.nid.preference.EncryptedPreferences.setContext(EncryptedPreferences.kt:67)
       at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:64)

**Comment by pparkppark** [comment]
혹시 앱에서 자체적으로 EncryptedSharedPreferences 를 사용하시나요?

**Comment by ehgusrkwhr** [comment]
아뇨 자체적으로 EncryptedSharedPreferences 사용하지 않습니다.

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.8.0에서 InvalidProtocolBufferException 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
