### ISSUE TITLE
[Bug Report] java.security.GeneralSecurityException: decryption failed

### ISSUE THREAD

**Issue by NickyXiao** [naver/naveridlogin-sdk-android#90]
# Bug Report
### 사용중인 네아로 SDK 버전
5.5.0
### 재현 시나리오
Crash collected on firebase

### Stack trace
```
Caused by java.security.GeneralSecurityException: decryption failed
       at com.google.crypto.tink.aead.AeadWrapper$WrappedAead.decrypt(AeadWrapper.java:83)
       at androidx.security.crypto.EncryptedSharedPreferences.getDecryptedObject(EncryptedSharedPreferences.java:535)
       at androidx.security.crypto.EncryptedSharedPreferences.getString(EncryptedSharedPreferences.java:413)
       at com.navercorp.nid.preference.EncryptedPreferences.get$default(EncryptedPreferences.kt:107)
       at com.navercorp.nid.preference.EncryptedPreferences.get(EncryptedPreferences.kt:107)
       at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:54)
       at com.navercorp.nid.preference.EncryptedPreferences.migration(EncryptedPreferences.kt:133)
       at com.navercorp.nid.preference.EncryptedPreferences.setContext(EncryptedPreferences.kt:67)
       at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:64)
       at com.klooklib.AllBizAppLifecycleCallback.onCreate(AllBizAppLifecycleCallback.kt:30)
       at com.klook.shell.AppLifecycleEventDispatcher.dispatchOnCreate(AppLifecycleEventDispatcher.kt:20)
       at com.klook.shell.KlookShellApplication.onCreate(KlookShellApplication.kt:101)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1123)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6467)
       at android.app.ActivityThread.-wrap2()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1969)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7383)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.8.0에서 GeneralSecurityException 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
