### ISSUE TITLE
5.7.0 login initialize crash

### ISSUE THREAD

**Issue by hxifrog** [naver/naveridlogin-sdk-android#99]
FATAL EXCEPTION: main
                                                                                                    Process: com.ifrog.soulpang, PID: 15241
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ifrog.soulpang/com.ifrog.soulpang.activity.HomeActivity}: javax.crypto.AEADBadTagException
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
                                                                                                    Caused by: javax.crypto.AEADBadTagException
                                                                                                    	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
                                                                                                    	at javax.crypto.Cipher.doFinal(Cipher.java:2113)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:118)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:101)
                                                                                                    	at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:919)
                                                                                                    	at com.google.crypto.tink.KeysetHandle.readWithAssociatedData(KeysetHandle.java:804)
                                                                                                    	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:785)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readMasterkeyDecryptAndParseKeyset(AndroidKeysetManager.java:381)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:297)
                                                                                                    	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:169)
                                                                                                    	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:130)
                                                                                                    	at com.navercorp.nid.preference.EncryptedPreferences.createSharedPreferences(EncryptedPreferences.kt:57)
                                                                                                    	at com.navercorp.nid.preference.EncryptedPreferences.init(EncryptedPreferences.kt:47)
                                                                                                    	at com.navercorp.nid.preference.EncryptedPreferences.access$init(EncryptedPreferences.kt:18)
                                                                                                    	at com.navercorp.nid.preference.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:31)
                                                                                                    	at com.navercorp.nid.preference.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:30)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.navercorp.nid.preference.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:30)
                                                                                                    	at com.navercorp.nid.preference.EncryptedPreferences.get(EncryptedPreferences.kt:109)
                                                                                                    	at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:54)
                                                                                                    	at com.navercorp.nid.preference.EncryptedPreferences.migration(EncryptedPreferences.kt:135)
                                                                                                    	at com.navercorp.nid.preference.EncryptedPreferences.setContext(EncryptedPreferences.kt:69)
                                                                                                    	at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:86)
                                                                                                    	at com.ifrog.soulpang.activity.HomeActivity.onCreate(HomeActivity.java:71)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8207)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8191)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
                                                                                                    Caused by: android.security.KeyStoreException: Signature/MAC verification failed
                                                                                                    	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1461)
                                                                                                    	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:186)
2023-09-11 15:34:43.191 15241-15241 AndroidRuntime          com.ifrog.soulpang                   E  	at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
                                                                                                    	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)

**Comment by DayeonLee-0** [comment]
안녕하세요.

네아로 SDK 담당자입니다.

네아로 SDK v5.8.0에서 AEADBadTagException 대한 예외 처리가 추가되었습니다.

개발에 참고 부탁드립니다.

감사합니다.
